
/*******************************************************************************
 * Copyright 2019 AMADEUS. All rights reserved.
 * Author: Paolo Iannino
 *******************************************************************************/

#ifndef CPMML_CPMML_H
#define CPMML_CPMML_H

#include <exception>
#include <memory>
#include <string>
#include <unordered_map>
#include <variant>
#include <vector>

namespace cpmml {
/**
 * cPMML version
 * Stores which version of the cPMML library is used.
 */
extern const std::string version;

/**
 * @brief Value type for model input fields.
 *
 * - std::string: a single scalar value (most fields)
 * - int: integer parameter (e.g. forecast horizon for time series)
 * - std::vector<std::string>: collection of items (transactional association)
 * - std::vector<double>: numeric series (e.g. regressor future values)
 */
using FieldValue = std::variant<std::string, int, std::vector<std::string>, std::vector<double>>;

/**
 * @brief Convenience alias for model input: field name -> value.
 */
using Input = std::unordered_map<std::string, FieldValue>;

/**
 * @class Exception
 * @brief Base class for all exceptions generated by cPMML.
 */
class Exception : public std::exception {
 public:
  /**
   * Constructs a new Exception object.
   * @param message explanatory string providing more details about the error.
   */
  explicit Exception(const std::string& message);

  /**
   * @return an explanatory string providing more details about the error.
   */
  virtual const char* what() const noexcept;

 private:
  /**
   * Explanatory string providing more details about the error.
   */
  std::string message;
};

/**
 * @class MissingValueException
 * @brief Reports errors related to the absence of values in user input.
 *
 * For instance a missing feature in a sample to be scored. Notice that,
 * depending on the underlying PMML, some models may tolerate missing values. It
 * is generated during model scoring.
 */
class MissingValueException : public Exception {
 public:
  /**
   * Constructs a new MissingValueException object.
   * @param message explanatory string providing more details about the error.
   */
  explicit MissingValueException(const std::string& message);
};

/**
 * @class InvalidValueException
 * @brief Reports errors related to the presence of wrong values in user input.
 *
 * For instance a categorical feature assuming a value not in the domain or
 * continuous features assuming a value outside certain boundaries. It is
 * generated during input validation or during model scoring.
 * @see Model#validate
 */
class InvalidValueException : public Exception {
 public:
  /**
   * Constructs a new InvalidValueException object.
   * @param message explanatory string providing more details about the error.
   */
  explicit InvalidValueException(const std::string& message);
};

/**
 * @class MathException
 * @brief Reports errors encountered in the computation of a mathematical
 * function. For example when a normalization methods receives wrong values.
 *
 */
class MathException : public Exception {
 public:
  /**
   * Constructs a new MathException object.
   * @param message explanatory string providing more details about the error.
   */
  explicit MathException(const std::string& message);
};

/**
 * @class ParsingException
 * @brief Reports errors related to the parsing of the user input or of the PMML
 * file representing the model.
 *
 * For instance this error could be triggered in case a certain PMML element or
 * attribute, needed for the scoring, is missing.
 *
 * @see Model
 */
class ParsingException : public Exception {
 public:
  /**
   * Constructs a new ParsingException object.
   * @param message explanatory string providing more details about the error.
   */
  explicit ParsingException(const std::string& message);
};
}  // namespace cpmml

class InternalScore;
namespace cpmml {

/**
 * @class Result
 * @brief Unified result of model evaluation.
 *
 * Wraps the output of any PMML model type: classification, regression,
 * clustering, association, anomaly detection, and time series forecasting.
 *
 * For standard models, use as_string(), as_double(), distribution(),
 * num_outputs(), str_outputs(). For time series models, use series() and
 * series_with_variance().
 */
class Result {
 public:
  Result() = default;

  explicit Result(const std::shared_ptr<InternalScore>& score);

  /**
   * @brief It returns the predicted value as a string.
   */
  std::string as_string() const;

  /**
   * @brief It returns the predicted value as a double. In case the predicted
   * value cannot be converted to double, it will return
   * std::numeric_limits<double>::min().
   */
  double as_double() const;

  /**
   * @brief Returns target categories and their associated probabilities.
   */
  std::unordered_map<std::string, double> distribution() const;

  /**
   * @brief Returns numeric output fields (probabilities, confidence, etc.).
   */
  std::unordered_map<std::string, double> num_outputs() const;

  /**
   * @brief Returns categorical (string) output fields.
   */
  std::unordered_map<std::string, std::string> str_outputs() const;

  /**
   * @brief Returns time series point forecasts.
   *
   * For non-time-series models, returns an empty vector.
   */
  std::vector<double> series() const;

  /**
   * @brief Returns time series forecasts with variance estimates.
   *
   * Each pair is {point_forecast, variance}. For non-time-series models,
   * returns an empty vector.
   */
  std::vector<std::pair<double, double>> series_with_variance() const;

  /**
   * @brief Returns true if the result contains no prediction.
   */
  bool empty() const;

 private:
  std::shared_ptr<InternalScore> score_;
};

// Backward compatibility alias
using Prediction = Result;
}  // namespace cpmml

class InternalEvaluator;
namespace cpmml {

/**
 *  @class  Model
 *  @brief  Class representing a PMML model.
 *
 *  Provides a single evaluate() entry point for all model types:
 *  classification, regression, clustering, association, anomaly detection,
 *  and time series forecasting.
 */
class Model {
 public:
  Model() = default;

  explicit Model(const std::string& model_filepath);

  /**
   * @brief Constructs a cpmml::Model instance representing the PMML model
   * stored at *model_filepath*.
   *
   * @param model_filepath path to the XML file containing the PMML model.
   * @param zipped whether the input file is compressed in zip format.
   *
   * @throws cpmml::ParsingException
   */
  Model(const std::string& model_filepath, const bool zipped);

  /**
   * @brief Evaluate the model against the given input arguments.
   *
   * This is the single entry point for all PMML model types.
   *
   * For standard models (classification, regression, clustering, etc.),
   * pass feature name/value pairs as strings:
   * @code{.cpp}
   * cpmml::Input sample = {{"age", "35"}, {"income", "50000"}};
   * cpmml::Result result = model.evaluate(sample);
   * std::string label = result.as_string();
   * @endcode
   *
   * For association models with transactional schemas, pass item baskets
   * as vector<string>:
   * @code{.cpp}
   * cpmml::Input basket = {{"item", std::vector<std::string>{"bread", "milk"}}};
   * cpmml::Result result = model.evaluate(basket);
   * @endcode
   *
   * For time series models, pass horizon (and optional regressors):
   * @code{.cpp}
   * cpmml::Input args = {{"horizon", 12}};
   * cpmml::Result result = model.evaluate(args);
   * auto forecast = result.series();  // vector<double> of length 12
   * @endcode
   *
   * @param arguments Input fields for the model. Default is empty (used by
   * time series models that need no external input beyond horizon).
   * @return cpmml::Result containing the prediction/forecast.
   *
   * @throws cpmml::InvalidValueException
   * @throws cpmml::MissingValueException
   * @throws cpmml::MathException
   * @throws cpmml::ParsingException
   */
  Result evaluate(const Input& arguments = {}) const;

  /**
   * @brief Validates user input against DataDictionary constraints.
   *
   * @param arguments Input fields to validate.
   * @return true if valid, false otherwise.
   */
  bool validate(const Input& arguments) const;

  /**
   * @brief Returns the name of the primary output field produced by this model.
   */
  std::string output_name() const;

  /**
   * @brief Returns the PMML mining function type as a string.
   *
   * Possible values: "CLASSIFICATION", "REGRESSION", "CLUSTERING",
   * "ASSOCIATION_RULES", "TIMESERIES", "MIXED".
   */
  std::string mining_function() const;

 private:
  std::shared_ptr<InternalEvaluator> evaluator;
};
}  // namespace cpmml

#endif
